# 新加入角色可自行添加
ElysianRealmConfig: 
  Human: 
    - 人律乐土
    - 爱律乐土
  Void: 
    - 空律乐土
    - 女王乐土
  Starry: 
    - 繁星乐土
    - 格蕾修乐土
    - 绘世乐土
  Disciplinary: 
    - 阿波尼亚乐土
    - 戒律乐土
  Golden: 
    - 伊甸乐土
    - 黄金乐土
  Felis: 
    - 帕朵乐土
    - 猫猫乐土
    - 帕朵菲利丝乐土
    - 菲利丝乐土
    - 猪咪乐土
  Oven: 
    - 火塔乐土
    - 烤箱乐土
    - 星棘乐土
    - 星塔乐土
  Palatinus: 
    - 天元乐土
    - 天鹅乐土
    - 泥头鹅乐土
  Silverwing: 
    - 大鸭鸭乐土
    - 次生银翼乐土
  Carol: 
    - 卡萝尔乐土
  Lnfinite: 
    - 梅比乌斯乐土
    - 蛇蛇乐土
  Raven: 
    - 渡鸦乐土
  Thunder: 
    - 雷律乐土
  Thunder_Attack: 
    - 雷律乐土3
    - 雷律平A流
  Thunder_Punishment: 
    - 雷律乐土2
    - 雷律天罚流
  Rosemary: 
    - 迷迭乐土
  Delta: 
    - 萝莎莉娅乐土
    - 粉毛乐土
    - 德尔塔乐土
  Anchora: 
    - 星锚乐土
    - 星猫乐土
  Elysia: 
    - 爱莉乐土
    - 爱莉希雅乐土
  Flamescion: 
    - 炎律乐土
    - 薪炎乐土
  Sentience: 
    - 识律乐土
    - 识宝乐土
  Starchasm: 
    - 奶希乐土
    - 冰希乐土
  Fischl: 
    - 皇女乐土
    - 菲谢尔乐土
  TwinSeele: 
    - 双生乐土
    - 黑希乐土
  Excelsis: 
    - 幽兰戴尔乐土
    - 月魄乐土
    - 呆鹅乐土
  Twilight: 
    - 月煌乐土
    - 紫苑乐土
  Kallen: 
    - 今样乐土
    - 卡莲乐土
  Moment: 
    - 勿忘乐土
    - 机八乐土
    - 冰八乐土
    - 八重樱乐土
  Refrigerator: 
    - 月魂乐土
    - 冰箱乐土
    - 冰塔乐土
  Bladestrike: 
    - 强袭乐土
  LunaKindred: 
    - 月下乐土
  Reason: 
    - 理律乐土
    - 摩托鸭乐土
    - 车车乐土
  Gloria: 
    - 荣光乐土
  Human_Branch: 
    - 人律乐土2
    - 人律蓄力流
    - 人律纯蓄流
    - 人律蓄力
    - 爱律乐土2
  Susang: 
    - 李素裳乐土
    - 月痕乐土
  Helical: 
    - 维尔薇乐土
    - 维尔微乐土
    - v2v乐土
  Void_Skill: 
    - 女王乐土2
    - 女王大招流
    - 空律大招流
  Eclipse: 
    - 姬子乐土
    - 真红乐土
    - 月蚀乐土
  Cabbage: 
    - 包菜乐土
    - 爱酱乐土
    - 爱衣乐土
  Truth: 
    - 真理乐土
    - 真律乐土
    - 真鸭乐土
    - 真理之律者乐土
  Serenade: 
    - 冰卡乐土
    - s卡乐土
    - S卡乐土
    - 怪盗乐土
    - 舞卡乐土
  Truth_Weapon: 
    - 真理乐土2
    - 真理武器流
    - 真律武器流
    - 真鸭武器流
    - 真理之律者武器流
  Eclipse_Branch: 
    - 真红乐土2
    - 姬子蓄力流
    - 真红蓄力流
    - 月蚀蓄力流
  First: 
    - 始源乐土
    - 始源大招流
    - 始源大招流乐土
  First_Branch: 
    - 始源乐土2
    - 始源之律者乐土
    - 始源分支流
    - 始源蓄力流
    - 始源分支流乐土
  Finally: 
    - 终焉乐土
    - 终焉之律者乐土
  Finally_Branch: 
    - 终焉乐土2
    - 终焉分支流
    - 终焉蓄力流
    - 终焉分支流乐土
  ShadowKnight: 
    - 月轮乐土
  Susana: 
    - 苏莎娜乐土
    - 苏珊娜乐土
    - 热砂乐土
  Dreamweaver: 
    - 羽兔乐土2
    - 羽兔投矛流
    - 羽兔大招流
  Dreamweaver_Weapon: 
    - 羽兔乐土
    - 羽兔摇旗流
    - 羽兔武器流
  TerminalAide0017: 
    - 0017乐土
    - 终末乐土
    - 终末协理乐土
    - 普罗米修斯乐土
    - 普鸭乐土
  ShigureKira: 
    - 时雨绮罗乐土
    - 时雨绮罗大招流
    - 时雨乐土
    - 绮罗乐土
  ShigureKira_Branch: 
    - 绮罗乐土2
    - 时雨绮罗乐土2
    - 时雨绮罗蓄力流
    - 时雨绮罗分支流
    - 绮罗分支流
  Rebirth_Life: 
    - 死律乐土3
    - 死律塑灵流
    - 死律塑灵流乐土
    - 塑灵流乐土
    - 死生之律者乐土
  Rebirth_Death: 
    - 死律乐土2
    - 死生之律者乐土2
    - 死律结命流
    - 死律结命流乐土
    - 结命流乐土
    - 死律安愈流
  Rebirth_Swap: 
    - 死律乐土4
    - 死律凋换流
    - 死律凋换流乐土
    - 凋换流乐土
  Sirin_Attack: 
    - 西琳乐土2
    - 河豚乐土2
    - 西琳普攻流
  Sirin_Branch: 
    - 西琳乐土
    - 河豚乐土
    - 西琳蓄力流
    - 西琳分支流
  Sentience_brick: 
    - 识律板砖流
    - 识律乐土2
  CosmicExpression_Parry: 
    - 大格蕾修乐土
    - 大格蕾修弹反流
  CosmicExpression_Attack: 
    - 大格蕾修乐土2
    - 大格蕾修普攻流
  Sentience_HoeFlow: 
    - 识律锄地流
    - 识律乐土3
  CosmicExpression_Mixed: 
    - 大格蕾修混合流
    - 大格蕾修乐土3
  Vicissitude_Branch: 
    - 崩符乐土2
    - 崩落华乐土2
    - 火符乐土2
    - 鸡妈妈乐土2
    - 崩符蓄力流
    - 火符蓄力流
  Vicissitude_Attack: 
    - 崩符乐土
    - 崩落华乐土
    - 火符乐土
    - 鸡妈妈乐土
    - 崩符普攻流
    - 火符普攻流
  Senadina: 
    - 希娜狄雅乐土
    - 希娜乐土
    - 希娜婶婶乐土
    - 曙光乐土
  Coralie: 
    - 科拉莉乐土
    - 重机乐土
    - 火锤乐土
    - 拉莉乐土
    - 臭鼬乐土
  Coralie_AstralRing: 
    - 科拉莉乐土2
    - 重机乐土2
    - 火锤乐土2
    - 拉莉乐土2
    - 臭鼬乐土2
    - 科拉莉星环流
  Thelema_AstralRing: 
    - 瑟莉姆乐土2
    - 瑟小姐乐土2
    - 瑟瑟乐土2
    - 瑟莉姆星环流
  Thelema: 
    - 瑟莉姆乐土
    - 瑟小姐乐土
    - 瑟瑟乐土
  Helia: 
    - 赫丽娅乐土
    - 巡矢乐土
    - 电弩乐土
  Helia_AstralRing: 
    - 赫丽娅乐土2
    - 巡矢乐土2
    - 电弩乐土2
    - 赫丽娅星环流
  Lantern: 
    - 莎芙莱乐土
    - 灯姐乐土
    - 灯乐土
    - 老灯乐土
    - 发光蘑菇头乐土
  Lantern_AstralRing: 
    - 莎芙莱乐土2
    - 灯姐乐土2
    - 灯乐土2
    - 老灯乐土2
    - 发光蘑菇头乐土2
    - 灯姐星环流
    - 莎芙莱星环流
    - 灯星环流
  Songque: 
    - 松雀乐土
    - 松雀奶奶乐土
  Songque_AstralRing: 
    - 松雀乐土2
    - 松雀奶奶乐土2
    - 松雀星环流
    - 松雀奶奶星环流
  Theresa_Sleep: 
    - 德丽莎乐土
    - 德丽傻乐土
    - 雷傻乐土
    - 量子傻乐土
    - 德丽莎睡觉流
    - 德丽傻睡觉流
    - 德莉傻乐土
    - 德莉莎乐土
  Theresa_AstralRing: 
    - 德丽莎乐土2
    - 德丽傻乐土2
    - 雷傻乐土2
    - 量子傻乐土2
    - 德丽莎星环流
    - 德丽傻星环流
    - 德莉傻乐土2
    - 德莉莎乐土2
  Vita: 
    - 薇塔乐土
    - 坏女人乐土
  Vita_AstralRing: 
    - 薇塔乐土2
    - 薇塔星环流
    - 坏女人乐土2
  Sparkle: 
    - 花火乐土
  Sparkle_AstralRing: 
    - 花火乐土2
    - 花火星环流
  Durandal_TakeWalk: 
    - 小呆鹅乐土
    - 迷你鹅乐土
    - 小呆鹅逛街流
  Durandal_Branch: 
    - 小呆鹅乐土2
    - 迷你鹅乐土2
    - 小呆鹅蓄力流
  Human_AstralRing: 
    - 人律星环流
    - 人律乐土3
  Kiana_Jump: 
    - 琪亚娜乐土
    - 琪天大圣乐土
    - 琪亚娜跳鼓流
    - 琪天大圣跳鼓流
    - 星琪乐土
    - 大懒猫乐土
  Kiana_Attack: 
    - 琪亚娜乐土2
    - 琪天大圣乐土2
    - 琪亚娜普攻流
    - 琪天大圣普攻流
    - 星琪乐土2
    - 大懒猫乐土2
  PeregrineSword: 
    - 李素裳乐土2
    - 一客逍游乐土
    - 李大枕头乐土
  PeregrineSword_AstralRing: 
    - 李素裳乐土3
    - 李素裳星环流
    - 一客逍游乐土2
    - 李大枕头乐土2
  CoralieDragon: 
    - 科拉莉乐土3
    - 龙科乐土
    - 魔龙乐土
    - 小龙女乐土
  CoralieDragon_AstralRing: 
    - 科拉莉乐土4
    - 龙科星环流
    - 龙科乐土2
    - 魔龙星环流
    - 小龙女星环流
  HeliaReborn: 
    - 赫丽娅乐土3
    - 机赫乐土
    - 龙骑士乐土
    - s赫乐土
  HeliaReborn_AstralRing: 
    - 赫丽娅乐土4
    - 机赫星环流
    - 龙骑士星环流
    - s赫星环流
  Rebirth_AstralRing: 
    - 死律乐土5
    - 死律星环流
  Rebirth: 
    - 死律乐土
  LoveELF: 
    - 爱愿妖精乐土
    - 爱愿乐土
    - 爱神乐土
  LoveELF_AstralRing: 
    - 爱愿妖精乐土2
    - 爱愿乐土2
    - 爱神乐土2
    - 爱愿星环流
  Rita_MissEspionage: 
    - 虚塔乐土
    - 特丽乐土
    - 色律乐土
  Rita_MissEspionage_AstralRing: 
    - 虚塔乐土2
    - 特丽乐土2
    - 色律乐土2
    - 特丽星环流
  TheresaLuna_Weapon: 
    - 月下誓约乐土
    - 月下誓约武器流
    - 大月下武器流
  TheresaLuna_Attack: 
    - 月下誓约普攻流
    - 大月下普攻流
  Mei_DawnbearingCrescent: 
    - 星芽乐土
    - 新芽乐土
  Mei_DawnbearingCrescent_AstralRing: 
    - 星芽乐土2
    - 新芽乐土2
    - 星芽星环流
  TheresaLuna: 
    - 大月下乐土
  TheresaLuna_AstralRing: 
    - 大月下乐土2
    - 大月下星环流
